version: '2'
services:
    just2trade-app:
        image: just2trade
        external_links:
            - just2trade-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/just2trade?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    just2trade-mysql:
        extends:
            file: mysql.yml
            service: just2trade-mysql
