just2trade-mysql:
  container_name: just2trade-mysql
  image: mysql:5.7.9
  # volumes:
  #   - ~/volumes/jhipster/just2trade/mysql/:/var/lib/mysql/
  environment:
    - MYSQL_USER=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=just2trade
  ports:
    - "3306:3306"
  command: mysqld --lower_case_table_names=1
